 git add   article/morph_analysis.py
 git add   article/static/01.pyc颇老积己.txt
 git add   article/static/02.颇捞姐沥府.txt
 git add   article/static/article/cnvt_tpc_exec.js
 git add   article/static/article/common.js
 git add   article/static/article/css/cnvt_tpc_exec.css
 git add   article/static/article/css/feedback_english.css
 git add   article/static/article/css/living_english.css
 git add   article/static/article/css/navigator_word.css
 git add   article/static/article/css/test_english.css
 git add   article/static/article/css/word_check.css
 git add   article/static/article/css/word_class.css
 git add   article/static/article/css/word_detail.css
 git add   article/static/article/feedback_english.js
 git add   article/static/article/living_english.js
 git add   article/static/article/navigator_word.js
 git add   article/static/article/test_english.js
 git add   article/static/article/word_check.js
 git add   article/static/article/word_class.js
 git add   article/static/article/word_detail.js
 git add   article/templates/article.html
 git add   article/templates/cnvt_tpc_exec.html
 git add   article/templates/feedback_english.html
 git add   article/templates/living_english.html
 git add   article/templates/navigator_word.html
 git add   article/templates/test_english.html
 git add   article/templates/word_check.html
 git add   article/templates/word_detail.html
 git add   article/tests.py
 git add   article/views.py
 git add   article/views_five_feedback.py
 git add   article/views_five_test.py
 git add   balance/admin.py
 git add   balance/apps.py
 git add   balance/models.py
 git add   balance/static/balance/b_style.css
 git add   balance/templates/balance.html
 git add   balance/tests.py
 git add   balance/views.py
 git add   hello/admin.py
 git add   hello/apps.py
 git add   hello/models.py
 git add   hello/tests.py
 git add   hello/views.py
 git add   index/admin.py
 git add   index/apps.py
 git add   index/models.py
 git add   index/templates/index.html
 git add   index/templates/力格绝澜2.txt
 git add   index/templates/力格绝澜3.txt
 git add   index/templates/力格绝澜5.txt
 git add   index/templates/力格绝澜6.txt
 git add   index/tests.py
 git add   index/views.py
 git add   main.py
 git add   manage.py
 git add   mdl_common/common_morph_process.py
 git add   mdl_login_info/apps.py
 git add   mdl_login_info/views.py
 git add   mdl_sql_mapping/__init__.py
 git add   mdl_sql_mapping/sql_mapping.py
 git add   mdl_sql_mapping/sql_mapping_article.py
 git add   mdmproj1/asgi.py
 git add   mdmproj1/settings.py
 git add   mdmproj1/urls.py
 git add   mdmproj1/wsgi.py
 git add   requirements.txt
 git add   serve.py
 git add   static/login_info/js/login_info.js
 git add   static/login_info/js/register_info.js
 git add   templates/registration/login.html
 git add   templates/registration/register.html