 git checkout --theirs  article/morph_analysis.py
 git checkout --theirs  article/static/01.pyc颇老积己.txt
 git checkout --theirs  article/static/02.颇捞姐沥府.txt
 git checkout --theirs  article/static/article/cnvt_tpc_exec.js
 git checkout --theirs  article/static/article/common.js
 git checkout --theirs  article/static/article/css/cnvt_tpc_exec.css
 git checkout --theirs  article/static/article/css/feedback_english.css
 git checkout --theirs  article/static/article/css/living_english.css
 git checkout --theirs  article/static/article/css/navigator_word.css
 git checkout --theirs  article/static/article/css/test_english.css
 git checkout --theirs  article/static/article/css/word_check.css
 git checkout --theirs  article/static/article/css/word_class.css
 git checkout --theirs  article/static/article/css/word_detail.css
 git checkout --theirs  article/static/article/feedback_english.js
 git checkout --theirs  article/static/article/living_english.js
 git checkout --theirs  article/static/article/navigator_word.js
 git checkout --theirs  article/static/article/test_english.js
 git checkout --theirs  article/static/article/word_check.js
 git checkout --theirs  article/static/article/word_class.js
 git checkout --theirs  article/static/article/word_detail.js
 git checkout --theirs  article/templates/article.html
 git checkout --theirs  article/templates/cnvt_tpc_exec.html
 git checkout --theirs  article/templates/feedback_english.html
 git checkout --theirs  article/templates/living_english.html
 git checkout --theirs  article/templates/navigator_word.html
 git checkout --theirs  article/templates/test_english.html
 git checkout --theirs  article/templates/word_check.html
 git checkout --theirs  article/templates/word_detail.html
 git checkout --theirs  article/tests.py
 git checkout --theirs  article/views.py
 git checkout --theirs  article/views_five_feedback.py
 git checkout --theirs  article/views_five_test.py
 git checkout --theirs  balance/admin.py
 git checkout --theirs  balance/apps.py
 git checkout --theirs  balance/models.py
 git checkout --theirs  balance/static/balance/b_style.css
 git checkout --theirs  balance/templates/balance.html
 git checkout --theirs  balance/tests.py
 git checkout --theirs  balance/views.py
 git checkout --theirs  hello/admin.py
 git checkout --theirs  hello/apps.py
 git checkout --theirs  hello/models.py
 git checkout --theirs  hello/tests.py
 git checkout --theirs  hello/views.py
 git checkout --theirs  index/admin.py
 git checkout --theirs  index/apps.py
 git checkout --theirs  index/models.py
 git checkout --theirs  index/templates/index.html
 git checkout --theirs  index/templates/力格绝澜2.txt
 git checkout --theirs  index/templates/力格绝澜3.txt
 git checkout --theirs  index/templates/力格绝澜5.txt
 git checkout --theirs  index/templates/力格绝澜6.txt
 git checkout --theirs  index/tests.py
 git checkout --theirs  index/views.py
 git checkout --theirs  main.py
 git checkout --theirs  manage.py
 git checkout --theirs  mdl_common/common_morph_process.py
 git checkout --theirs  mdl_login_info/apps.py
 git checkout --theirs  mdl_login_info/views.py
 git checkout --theirs  mdl_sql_mapping/__init__.py
 git checkout --theirs  mdl_sql_mapping/sql_mapping.py
 git checkout --theirs  mdl_sql_mapping/sql_mapping_article.py
 git checkout --theirs  mdmproj1/asgi.py
 git checkout --theirs  mdmproj1/settings.py
 git checkout --theirs  mdmproj1/urls.py
 git checkout --theirs  mdmproj1/wsgi.py
 git checkout --theirs  requirements.txt
 git checkout --theirs  serve.py
 git checkout --theirs  static/login_info/js/login_info.js
 git checkout --theirs  static/login_info/js/register_info.js
 git checkout --theirs  templates/registration/login.html
 git checkout --theirs  templates/registration/register.html